cunla/fakeredis-py

fakeredis/_aioredis2.py
fakeredis/aioredis.py

Make fakeredis work with redis.asyncio in redis 4.2+

fix: work with redis.asyncio

---

fakeredis/_commands.py
fakeredis/_fakesocket.py
poetry.lock
pyproject.toml
test/test_fakeredis6.py
test/test_hypothesis.py
test/test_redispy4_plus.py

Zrange byscore

---

fakeredis/_basefakesocket.py
fakeredis/_server.py
poetry.lock
pyproject.toml
test/test_init_args.py

Remove six dependency and adding host to `conn_pool_args`

---

fakeredis/_basefakeluasupport.py
fakeredis/_fakesocket.py
poetry.lock
pyproject.toml

Separate LUA support to a different file

---

poetry.lock
test/test_redispy4_plus.py

Test get float-type behavior

---

REDIS_COMMANDS.md
fakeredis/_basefakesocket.py
fakeredis/_fakeluasocket.py
fakeredis/_fakesocket.py
test/test_sorted_set_cmds.py

Implement `BZPOPMIN`/`BZPOPMAX` support

Implement `BZPOPMIN`/`BZPOPMAX` support

---

.gitignore
fakeredis/__init__.py
fakeredis/_helpers.py
fakeredis/aioredis.py
fakeredis/commands_mixins/sortedset_mixin.py
poetry.lock
pyproject.toml

Add mypy support

---

.github/workflows/test.yml
fakeredis/_basefakesocket.py
fakeredis/_helpers.py
fakeredis/commands_mixins/scripting_mixin.py
fakeredis/stack/_json_mixin.py
test/json/test_json.py
test/json/test_json_commands.py

Implement json.mget

---

REDIS_COMMANDS.md
fakeredis/_basefakesocket.py
fakeredis/_commands.py
fakeredis/_msgs.py
fakeredis/stack/_json_mixin.py
poetry.lock
pyproject.toml
test/json/test_json.py
test/json/test_json_commands.py

Implement `JSON.CLEAR`

---

.github/workflows/test.yml
REDIS_COMMANDS.md
fakeredis/_msgs.py
fakeredis/commands_mixins/string_mixin.py
test/test_mixins/test_string_commands.py

Implement LCS

---

fakeredis/_msgs.py
fakeredis/commands_mixins/bitmap_mixin.py
test/test_mixins/test_bitmap_commands.py

Implement support for `BITPOS` (bitmap command)

---

fakeredis/stack/_json_mixin.py
test/test_json/test_json.py

Fix encoding of None

---

docs/about/changelog.md
docs/redis-stack.md
fakeredis/stack/__init__.py
fakeredis/stack/_json_mixin.py
pyproject.toml

Fix import error for NoneType

---

.github/workflows/test.yml
poetry.lock
pyproject.toml

Add support for redis-py 4.5

---

fakeredis/aioredis.py
poetry.lock
pyproject.toml
test/test_redis_asyncio.py

Fix async_timeout usage on py3.11

---

fakeredis/aioredis.py
test/test_redis_asyncio.py

Fixes user/password auth error for aioredis similar to:
https://github.com/cunla/fakeredis-py/issues/9

Fix creating fakeredis.aioredis using url with user/password

---

fakeredis/_stream.py
test/test_mixins/test_streams_commands.py

Implemented fix for #151 and added unit test to cover fix.
Fix #151

Fixed xadd timestamp (fixes #151)

---

docs/about/changelog.md
docs/redis-commands/Redis.md
fakeredis/_command_args_parsing.py
fakeredis/_msgs.py
fakeredis/_stream.py
fakeredis/commands_mixins/streams_mixin.py
fakeredis/commands_mixins/string_mixin.py
pyproject.toml
test/test_mixins/test_streams_commands.py

Fix #168
Fix #165 
Fix #161
Fix #164

Implement `XGROUP CREATE`, `XGROUP SETID`, `XGROUP CREATE`, `XINFO GROUPS`

---

docs/about/changelog.md
docs/redis-commands/Redis.md
docs/redis-commands/RedisJson.md
fakeredis/aioredis.py
scripts/supported2.py
test/test_redis_asyncio.py

fix:add support for version argument

---

docs/about/changelog.md
docs/redis-commands/Redis.md
fakeredis/_msgs.py
fakeredis/commands_mixins/list_mixin.py
test/test_mixins/test_list_commands.py

feat:implement `LPOS`

---

docs/about/changelog.md
docs/redis-commands/Redis.md
fakeredis/commands_mixins/list_mixin.py
test/test_mixins/test_list_commands.py

Implement `LMPOP` and `BLMPOP`

---

fakeredis/_commands.py
fakeredis/_zset.py
test/test_mixins/test_sortedset_commands.py
test/test_mixins/test_transactions_commands.py

fix:issue with ZRANGE and ZRANGESTORE with BYLEX

---

docs/about/changelog.md
fakeredis/_server.py
fakeredis/aioredis.py
test/test_redis_asyncio.py

fix:bug using same server with aioredis

---

docs/about/changelog.md
fakeredis/_basefakesocket.py
fakeredis/commands_mixins/streams_mixin.py
test/test_mixins/test_streams_commands.py

Fix blocking xreadgroup

---

fakeredis/commands_mixins/streams_mixin.py
test/test_mixins/test_streams_commands.py

fix:xread bug

---

fakeredis/commands_mixins/streams_mixin.py
test/test_mixins/test_streams_commands.py

fix:xread blocking

---

docs/index.md

Update documentation to include [`django-redis`](https://github.com/jazzband/django-redis) use case.

Update Django cache documentation

---

docs/index.md

docs: Full code for FastAPI integration

---

docs/about/changelog.md
docs/requirements.txt
fakeredis/aioredis.py
fakeredis/commands_mixins/connection_mixin.py
poetry.lock
pyproject.toml
test/test_asyncredis.py

fix:bug with responses written twice in async redis connection

---

docs/about/changelog.md
fakeredis/commands_mixins/streams_mixin.py
pyproject.toml
test/test_mixins/test_streams_commands.py

fix:xreadgroup when stream length is less than COUNT 

---

docs/about/changelog.md
fakeredis/_basefakesocket.py
fakeredis/_commands.py
fakeredis/commands_mixins/generic_mixin.py
fakeredis/commands_mixins/hash_mixin.py
fakeredis/commands_mixins/set_mixin.py
fakeredis/commands_mixins/sortedset_mixin.py
fakeredis/model/__init__.py
fakeredis/model/_expiring_members_set.py
fakeredis/model/_hash.py
fakeredis/server_specific_commands/dragonfly_mixin.py
test/test_mixins/test_set_commands.py

SADDEX - implement set with support for expiring members

---

docs/about/changelog.md
fakeredis/_connection.py
fakeredis/model/_stream.py
fakeredis/stack/_json_mixin.py
pyproject.toml
test/test_json/test_json.py

fix:json.set nx arg

---

docs/about/changelog.md
fakeredis/_connection.py
fakeredis/aioredis.py
pyproject.toml
test/test_asyncredis.py

Addresses #384 - checking default values in `__init__`

fix:aioredis.FakeRedis uses inspect for `__init__` parameters

---

test/test_asyncredis.py

Replace the deprecated `event_loop` fixture with an explicit call to `asyncio.get_running_loop()`, as suggested by the deprecation warnings:
```
test/test_asyncredis.py:61
test/test_asyncredis.py:61: PytestDeprecationWarning: test_pubsub[fake] is asynchronous and explicitly requests the "event_loop" fixture. Asynchronous fixtures and test functions should use "asyncio.get_running_loop()" instead.
async def test_pubsub(async_redis, event_loop):
```
This fixes compatibility with `pytest-asyncio >= 1.0.0`.

test: Replace deprecated `event_loop` fixture
