setup.cfg, tox.ini
According to [`.github/workflows/test.yml`](https://github.com/dsoftwareinc/fakeredis-py/blob/master/.github/workflows/test.yml), fakeredis with python 3.7 has not been tested anymore since the release of the latest stable: v1.7.5. However, pypi says fakeredis still supports python 3.7, which comes from `setup.cfg`.
=> Remove Python 3.7

test/test_fakeredis.py
Tests for `lmove` operation failed (see #11) due to redis-py version.
Create annotation for supporting tests from v4.1.2 and above.
See [redis-py changes in v4.1.2](https://github.com/redis/redis-py/blob/40fdb152641fcdf3be010cebe656331aa5709c2d/CHANGES#L19-L22)
=> Create annotation for redis4+ tests

.github/workflows/publish.yml
Incorporates the changes from #31 since I had overlooked that there was already a release action. This would make it more obvious that this run failed: https://github.com/dsoftwareinc/fakeredis-py/actions/runs/2449338320
=> Update publish GitHub action to create an issue on failure

fakeredis/_helpers.py, test/test_lua.py
Cursors are bytes in redis: https://redis.io/commands/scan/
=> Fix input and output type of cursors for SCAN commands

fakeredis/_fakesocket.py, poetry.lock, pyproject.toml, test/test_fakeredis6.py
PR adds support for [`ZMSCORE`](https://redis.io/commands/zmscore/) (available since [`redis-py 4.0.0`](https://github.com/redis/redis-py/blob/master/CHANGES#L121)) and [associated](https://github.com/the-wondersmith/fakeredis-py/blob/zmscore/test/test_fakeredis6.py#L2120) [Hypothesis](https://hypothesis.readthedocs.io/en/latest)-based tests.
=> Implement support for `zmscore`

fakeredis/aioredis.py, test/test_redis_asyncio.py
please check this.
relative pr https://github.com/redis/redis-py/pull/2356
without this, you can meet this
<details>
<summary>redis/asyncio/connection.py:767: TypeError
</summary>
```py3
async def send_packed_command(
self, command: Union[bytes, str, Iterable[bytes]], check_health: bool = True
) -> None:
if not self.is_connected:
await self.connect()
elif check_health:
await self.check_health()
try:
if isinstance(command, str):
command = command.encode()
if isinstance(command, bytes):
command = [command]
if self.socket_timeout:
await asyncio.wait_for(
self._send_packed_command(command), self.socket_timeout
)
else:
self._writer.writelines(command)
await self._writer.drain()
except asyncio.TimeoutError:
await self.disconnect(nowait=True)
raise TimeoutError("Timeout writing to socket") from …
```
=> fix: add nowait for asyncio disconnect

REDIS_COMMANDS.md, fakeredis/commands_mixins/string_mixin.py, scripts/create_issues.py, test/test_mixins/test_server_commands.py, test/test_mixins/test_string_commands.py
=> Implement GETEX

fakeredis/stack/_json_mixin.py, test/test_json/test_json.py
Fix AssertionError in _run_command when mget returns a dict within the list of results.
Can be reproduced by running this script. I would expect the output to be `[[5, 8, {"b": "nested3"}]]`.
```import fakeredis
r = fakeredis.FakeStrictRedis(version=7)
r.json().set(
"doc3", "$", {
"a": 5,
"b": 5,
"nested": {
"a": 8
},
"c": None,
"nested2": {
"a": {
"b": "nested3"
}
}
})
print(r.json().mget(["doc3"], "$..a"))
```
This is my first PR so please don't be to harsh. :)
=> Fix json mget when dict is returned

fakeredis/__init__.py
Fixes https://github.com/cunla/fakeredis-py/issues/115
There is a good explanation of the issue here: https://github.com/unionai-oss/pandera/pull/686
TLDR; Pylance/Pyright uses `__all__` as a indicator of public exports.
=> fix: properly export

fakeredis/_msgs.py, fakeredis/commands_mixins/sortedset_mixin.py, fakeredis/commands_mixins/string_mixin.py, test/test_extract_args.py, test/test_mixins/test_sortedset_commands.py
=> Add support for zrange arguments

fakeredis/commands_mixins/generic_mixin.py, test/test_mixins/test_generic_commands.py
Fix a module import used un `GenericCommandsMixin.randomkey`
When executing the `RANDOMKEY` command with `FakeRedis`, an exception is thrown.
`AttributeError: 'builtin_function_or_method' object has no attribute 'choice'`
This issue was introduced in `v1.10.0`
Execute the `.randomkey()` method (or command) using `FakeRedis`
Assume this `pytest` test
```py
def test_randomkey_returns_existing_key(r):
r.set("foo", 1)
r.set("bar", 2)
r.set("baz", 3)
assert r.randomkey() in ("foo", "bar", "baz")  # boom!
```
=> Fix import used in GenericCommandsMixin.randomkey

fakeredis/_server.py, poetry.lock, pyproject.toml, test/test_general.py, test/test_init_args.py
=> Unique FakeServer when no connection params are provided

.github/workflows/publish.yml, .github/workflows/test.yml, docs/about/changelog.md, docs/redis-commands/Redis.md, docs/requirements.txt, fakeredis/_command_args_parsing.py, fakeredis/_stream.py, fakeredis/commands_mixins/bitmap_mixin.py, fakeredis/commands_mixins/connection_mixin.py, fakeredis/commands_mixins/generic_mixin.py, fakeredis/commands_mixins/hash_mixin.py, fakeredis/commands_mixins/list_mixin.py, fakeredis/commands_mixins/pubsub_mixin.py, fakeredis/commands_mixins/scripting_mixin.py, fakeredis/commands_mixins/server_mixin.py, fakeredis/commands_mixins/streams_mixin.py, fakeredis/commands_mixins/string_mixin.py, poetry.lock, pyproject.toml, test/test_mixins/test_streams_commands.py, test/test_redis_asyncio.py
=> Implement XREAD

fakeredis/_msgs.py, fakeredis/commands_mixins/streams_mixin.py, test/test_mixins/test_streams_commands.py
Fix #210
I'm having some difficulties with linters (loads of errors from <s>both flake8 and</s> mypy) and running the tests (one failure) before I made my changes. Probably I haven't set my environment up correctly: certainly tox didn't like it at all and failed to install anything.
My new test passes, the files I've touched lint OK, so I don't *think* I've made things any worse. But also the github workflow hasn't run in my repo, so I can't be sure. Therefore you might want to take this into a branch of your repo first and run tests yourself!
=> fix:formatting of error message about missing group

docs/about/changelog.md, docs/redis-commands/Redis.md, fakeredis/_msgs.py, fakeredis/commands_mixins/bitmap_mixin.py, test/test_mixins/test_bitmap_commands.py
One less command missing 😁
Note: this is not the most optional implementation, as writes are written bit by bit, needing up to 64 writes.  However this was done in the name of simplicity, specially considering how messed up is the overflow detection on the original REDIS codebase: https://github.com/redis/redis/blob/unstable/src/bitops.c#L288 (which here is contains a ton of modular arithmetic manipulation in order to make it compatible).
=> Implement BITFIELD

docs/index.md
Update the documentation to reflect that django test settings need to be set in the CONNECTION_POOL_KWARGS key
=> Update django cache integration documentation

docs/about/changelog.md, fakeredis/_server.py, fakeredis/aioredis.py, test/test_asyncredis.py
Fix #299. Revert the sync client back to _not_ sharing state by default, and make the async client work in the same way.
Also a quick minor fix of the link in the changelog which was taking users to a PR 299, rather than the PR that fixed issue 299.
Note that some of the _real_ Redis tests were failing for me locally but for seemingly unrelated parts of the code so I wasn't sure if that was just something to do with the Redis server on my local machine. Figured I'd see if they fail in CI before spending any time trying to debug them - if they still fail here I'm happy to address them!
=> Do not share state, by default, for sync or async clients

fakeredis/_server.py
This fixes issues when you have strongly typed client code using that method.
An example would be something like
```python
REDIS_ACTION_STORE_CLIENT: FakeRedis | RedisCluster | None = None
def get_redis_client() -> FakeRedis | RedisCluster:
if REDIS_ACTION_STORE_CLIENT is None:
redis_class: type[FakeRedis | RedisCluster] = (
FakeRedis
if getattr(settings, "REDIS_TEST_BACKEND", False)
else RedisCluster
)
REDIS_ACTION_STORE_CLIENT = redis_class.from_url(
url=settings.REDIS_ACTION_STORE_URL, encoding="utf-8", decode_responses=True
)
return REDIS_ACTION_STORE_CLIENT
```
Without this patch, mypy complains that an object of type `FakeRedisMixin` cannot be assigned to a variable of type `FakeRedis | RedisCluster`, even though the class we called it on is of type `FakeRedis` and the returned …
=> fix: FakeRedisMixin.from_url() return type is really Self.

fakeredis/_stream.py, test/test_mixins/test_streams_commands.py
[bisect_right](https://docs.python.org/3/library/bisect.html#bisect.bisect_right) has a bit different behaviour than bisect_left. Also code did not account for exclusive indexes from right
=> fix:xrevrange to work with exclusive ranges

fakeredis/_commands.py, fakeredis/commands_mixins/bitmap_mixin.py, test/test_mixins/test_bitmap_commands.py
Hey!  Thanks for the library! :rocket: 
I've recently been testing dragonfly's BITPOS implementation with fakeredis and stumbled upon some bugs in fakeredis's implementation, so I've decided to fix it.  The misbehaving is related to the clear bit mode i.e. when BITPOS command looking for 0 bit.
https://redis.io/docs/latest/commands/bitpos/
> If we look for clear bits (the bit argument is 0) and the string only contains bits set to 1, the function returns the first bit not part of the string on the right. So if the string is three bytes set to the value 0xff the command BITPOS key 0 will return 24, since up to bit 23 all the bits are 1.
> The function considers the right of the string as padded with zeros if you look for clear bits and specify no range or the start argument only.
> 
> …
=> fix:bug in bitpos function for the clear bit mode

fakeredis/aioredis.py, test/conftest.py, test/test_asyncredis.py
Mimics the code in the sync method to also skip decoding when requested.
https://github.com/cunla/fakeredis-py/blob/7a1ec28bed4c8f97754312691abd563332612c8d/fakeredis/_connection.py#L67
=> support disable_decoding in async read_response

test/test_tcp_server/test_connectivity.py
Fix `test_tcp_server_started` to use a context manager, in order to close the connection to the `TcpFakeServer` when done.  Otherwise, the test relies on GC closing the connection in order for the server thread to finish -- which does not happen with PyPy, and causes `pytest` to hang after running the test suite.
=> fix: Fix `test_tcp_server_started` to close the connection

.github/workflows/test.yml, docs/about/changelog.md, fakeredis/commands_mixins/hash_mixin.py, fakeredis/model/_acl.py, fakeredis/model/_hash.py, test/test_mixins/test_acl_commands.py, test/test_mixins/test_hash_expire_redispy6.py, test/test_mixins/test_server_commands.py, test/test_mixins/test_string_commands.py
=> feat:support for redis8 new hash commands

fakeredis/commands_mixins/hash_mixin.py, fakeredis/model/_hash.py, test/test_mixins/test_hash_commands.py, test/test_mixins/test_hash_expire_commands.py
Fix for [issue](https://github.com/cunla/fakeredis-py/issues/380): `hincrby` / `hincrbyfloat` commands now don't remove ttl from hash key.
=> Fix for 380 (hincrby removes hash key ttl)

pyproject.toml, test/conftest.py, uv.lock
This PR replaces the use of the `@pytest_asyncio.fixture` decorator with `@pytest.fixture` and bumps the dependency on pytest-asyncio to v1.1.0.
Closes #403
=> Update test dependency on pytest-asyncio to v1.1.0

test/conftest.py
Make it possible to run the test suite without `valkey` package, by moving the relevant imports out of the global `conftest.py` scope into the spot where it is used.  This is helpful for downstreams that currently do not package `valkey`.
=> test: Make valkey optional for testing

fakeredis/commands_mixins/generic_mixin.py, test/test_mixins/test_generic_commands.py
The expireat/pexpire/pexpireat functions don't accept the kwargs `nx`/`xx`/`gt`/`lt`, which doesn't match how these commands work in the redis python client. This functionality is actually already built for `expire`, but just wasn't plumbed through for the other 3 versions of this command. This PR fixes that.
=> Plumb through options for expireat/pexpire/pexpireat
